#!/bin/bash

# merge_med.data generates multiple med than it merge all med files into a single one
# decoup.data generates .Zones needed by merge_med.data, it is called by prepare
# seq.data runs a sequential computation
# verifie compares sequential med with merged med
if [ -f merge_med_ALL.med ]
then	

  # Run serial simulation
  trust seq.data 1>seq.out 2>seq.err

  # Comparisions seq & // med merging
  compare_lata seq_0000.med merge_med_ALL.med 1>verifie.log 2>&1 || exit -1

  numb_diff=`awk '$1=="Number"{print $5}' verifie.log`
  if [[ "$numb_diff" -gt "0" ]]
  then
    echo "Error ! The merge is not good and the seq-// med files are not identical !"
    exit -1
  else
    echo "All OK for the med merge !"
  fi
  
  # Compare seq & // cgns
  compare_cgns post_cgns_par.cgns post_cgns_seq.cgns 1>verifie_cgns.log 2>&1 || exit -1

  numb_diff=`awk '$1=="Number"{print $5}' verifie.log`
  if [[ "$numb_diff" -gt "0" ]]
  then
    echo "Error ! CGNS files are not identical !"
    exit -1
  else
    echo "All OK for the CGNS diff !"
  fi
  
  # Compare cgns & converted to lata 
  compare_cgns post_cgns_par.cgns post_lata_seq.lata 1>verifie_lata.log 2>&1 || exit -1

  numb_diff=`awk '$1=="Number"{print $5}' verifie.log`
  if [[ "$numb_diff" -gt "0" ]]
  then
    echo "Error ! CGNS/LATA files are not identical !"
    exit -1
  else
    echo "All OK for the CGNS/LATA diff !"
  fi
  
  # Run // simulation with other cgns option
  trust par_cgns.data 4 1>par_cgns.out 2>par_cgns.err
  
  # compare cgns with different options
  compare_cgns post_cgns_par.cgns par_cgns.cgns 1>verifie_cgns2.log 2>&1 || exit -1

  numb_diff=`awk '$1=="Number"{print $5}' verifie.log`
  if [[ "$numb_diff" -gt "0" ]]
  then
    echo "Error ! CGNS files are not identical !"
    exit -1
  else
    echo "All OK for the CGNS diff !"
  fi
  
  # Compare cgns (other option) & converted to lata 
  compare_cgns par_cgns.cgns post_lata_seq.lata 1>verifie_lata2.log 2>&1 || exit -1

  numb_diff=`awk '$1=="Number"{print $5}' verifie.log`
  if [[ "$numb_diff" -gt "0" ]]
  then
    echo "Error ! CGNS/LATA files are not identical !"
    exit -1
  else
    echo "All OK for the CGNS/LATA diff !"
  fi
  
  
  # test python loader
  echo "Testing python loader on cgns"
  source $TRUST_ROOT/env_for_python.sh
  
  python script_loader.py || exit -1
fi
