#!/usr/bin/env python3
"""
Customise the Doxygen HTML search-bar filter tabs.

Problem
-------
Doxygen produces a single monolithic search index that mixes narrative
documentation pages, keyword reference pages, C++ API symbols, and Python
API pages into one undifferentiated list.  For a project of TRUST's size
this makes the search bar hard to use.

What this script does
---------------------
It replaces Doxygen's default search index with **five categorised tabs**:

    All | Documentation | Keyword Reference | C++ API | Trustutils

Each tab has its own set of per-character ``.js`` shards (the files that the
Doxygen search widget loads on demand as the user types).

The script runs *after* Doxygen and *after* flatten_navtree.py, as the last
step of ``make run_doxygen`` in docs/Makefile.

How Doxygen's search index works
---------------------------------
Doxygen writes ``html/search/`` containing:

- ``searchdata.js``         — metadata: section names, labels, and which
                              first-characters have entries in each section.
- ``<section>_<hex>.js``   — per-section, per-first-character entry arrays.
                              <section> is a Doxygen-internal name such as
                              "pages", "classes", "functions", etc.
                              <hex> is the hex index of the first character
                              in the section's presence string.

Each entry file has the form::

    var searchData = [
      ["symbol_name", ["path/to/page.html#anchor", 1, "display title"]],
      ...
    ];

This script reads all of Doxygen's entry files, classifies every entry into
one of the five custom sections by URL-prefix matching, and writes a new set
of files named ``<custom_section_id>_<hex>.js``.  It then rewrites
``searchdata.js`` so the Doxygen search widget picks up the new sections
instead of the originals.

Usage
-----
    python3 patch_filter.py <doxygen-html-dir>
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------------------
# Section definitions
# ---------------------------------------------------------------------------
# Each entry is (section_id, display_label).
# - section_id is used as the filename prefix for the .js shards and as the
#   key in searchdata.js.
# - display_label is shown in the search-bar drop-down.
# Order determines the tab order in the UI.

SECTIONS = [
    ("custom_all",        "All"),
    ("trust_docs",        "Documentation"),
    ("trust_kwref",       "Keyword Reference"),
    ("trust_cppapi",      "C++ API"),
    ("trust_trustutils",  "Trustutils"),
]
# Unpack section IDs into named constants for use in RULES below.
CUSTOM_ALL, DOCS, KWREF, CPPAPI, TRUSTUTILS = [s[0] for s in SECTIONS]

# ---------------------------------------------------------------------------
# URL classification rules
# ---------------------------------------------------------------------------
# Each rule is (tuple-of-url-prefixes, target_section).
# Rules are checked in order; the first match wins.
# Entries that match no rule fall through to DOCS (Documentation).
#
# The URL used for matching is the bare HTML filename (no path, no fragment),
# derived from the "href" embedded in each search entry.
#
# Prefix rationale:
#   KeywordsReference / KW_  — Doxygen page IDs for the keyword reference hub
#                             and per-family sub-pages generated by trustify.
#   group__TRUSTUTILS       — The Doxygen group index page for TRUSTUTILS.
#   TRUSTUTILS_             — Per-module trustutils API pages (@page IDs).
#   Dev_ValidationFormAPI   — The trustutils API index page.
#   usergroup0 / class /    — Doxygen auto-generated C++ API pages: the C++
#   namespace / struct        API top-level tab, class pages, namespace pages,
#                             and struct pages.
#   citelist is intentionally left out: it is the bibliography page and belongs
#   in the Documentation tab, not the C++ API tab.

RULES = [
    (("KeywordsReference", "KW_"),                                      KWREF),
    (("group__TRUSTUTILS", "TRUSTUTILS_", "Dev_ValidationFormAPI"),    TRUSTUTILS),
    (("usergroup0", "class", "namespace", "struct"),                   CPPAPI),
]

# Doxygen's own section names for C++ symbol data.
# Entries coming from these sections are *always* routed to CPPAPI regardless
# of their URL, because they are exclusively populated by C++ source scanning.
CPP_SYMBOL_SECTIONS = {
    "classes", "namespaces", "files", "functions", "variables",
    "typedefs", "enums", "enumvalues", "related", "defines", "groups",
}

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def categorize(url: str) -> str:
    """Map a page URL to a custom section ID using RULES.

    Strips leading ``./``, removes any fragment (``#anchor``), takes the
    bare filename, then checks each rule's prefixes in order.

    Parameters
    ----------
    url : str
        Raw href value from a search entry, e.g. ``"./KW_interprete.html#kw_axi"``.

    Returns
    -------
    str
        One of the section ID constants (KWREF, TRUSTUTILS, CPPAPI, DOCS).
    """
    bare = url.lstrip("./").split("#")[0].split("/")[-1]
    for prefixes, section in RULES:
        if any(bare.startswith(p) for p in prefixes):
            return section
    return DOCS


def classify_entry(raw: str) -> str:
    """Extract the URL from a raw JS search entry and return its section ID.

    A search entry looks like::

        ["symbol", ["path/to/page.html#anchor", 1, "Title"]]

    This function locates the first ``'...'`` single-quoted string ending in
    ``.html`` (with an optional fragment) and passes it to ``categorize``.

    Parameters
    ----------
    raw : str
        One complete JS array literal from a searchData file.
    """
    m = re.search(r"\[\s*'([^']+\.html[^']*)'", raw)
    return categorize(m.group(1)) if m else DOCS


def first_char(raw: str) -> str:
    """Return the lowercase first character of a search entry's symbol name.

    Doxygen shards each section's entries by the first character of the
    symbol name so that the browser only loads the relevant shard as the
    user types.

    Parameters
    ----------
    raw : str
        One complete JS array literal from a searchData file.
        The symbol name is the first quoted string: ``["name", [...]]``.
    """
    m = re.match(r"\[\s*'(.)", raw)
    return m.group(1).lower() if m else "_"


def split_js_array(text: str) -> list:
    """Split a top-level JS array literal into its element strings.

    Doxygen's searchData arrays can contain deeply nested sub-arrays, so a
    simple ``split(",")`` would break on commas inside nested arrays.  This
    function counts bracket depth to find the boundaries of each top-level
    element.

    The walker is **string-aware**: characters inside ``'``- or ``"``-quoted
    string literals don't count toward depth.  C++ symbols like
    ``'operator[]'`` are common in Doxygen's search data; without this, a
    string with unbalanced ``[`` or ``]`` (rare but possible) would
    desynchronise the depth counter and corrupt the split — audit H5.

    The input is the full content of ``var searchData = [...];`` with the
    outer ``[`` and ``]`` stripped.  Each element is itself a ``[...]``
    array literal.

    Parameters
    ----------
    text : str
        The raw text of a searchData array (including its outer ``[ ]``).

    Returns
    -------
    list of str
        Each element is one ``[...]`` entry string, ready for further parsing.
    """
    entries, depth, start = [], 0, None
    text = text.strip().strip("[]")   # drop the outermost [ ]
    n = len(text)
    i = 0
    while i < n:
        c = text[i]
        if c == '"' or c == "'":
            # Skip the string literal (handle backslash escapes).
            quote = c
            i += 1
            while i < n and text[i] != quote:
                if text[i] == "\\" and i + 1 < n:
                    i += 2
                    continue
                i += 1
            i += 1  # step past the closing quote
            continue
        if c == "[":
            if depth == 0:
                start = i            # record start of a new top-level element
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0 and start is not None:
                entries.append(text[start : i + 1])
                start = None
        i += 1
    return entries


def read_js(path: Path):
    """Read a searchData JS file and return the raw array text, or None.

    The expected file format is::

        var searchData =
        [
          [...],
          ...
        ];

    Parameters
    ----------
    path : Path
        Path to a ``*_<hex>.js`` shard file.

    Returns
    -------
    str or None
        The ``[...]`` array text if found, otherwise None (e.g. empty file).
    """
    m = re.search(
        r'var searchData\s*=\s*(\[.*\])\s*;',
        path.read_text(encoding="utf-8"),
        re.DOTALL,
    )
    return m.group(1) if m else None


def write_files(search_dir: Path, name: str, char_map: dict, presence: str) -> None:
    """Write per-character shard ``.js`` files for one custom section.

    Doxygen names each shard ``<section>_<hex_index>.js`` where the hex index
    is the position of the first character in the section's *presence string*
    (a sorted string of all first characters that have at least one entry).
    For example, if a section has entries starting with 'a', 'c', and 'f',
    the presence string is ``"acf"`` and the shards are named
    ``<section>_0.js``, ``<section>_1.js``, ``<section>_2.js``.

    Parameters
    ----------
    search_dir : Path
        The ``html/search/`` directory.
    name : str
        Section ID prefix, e.g. ``"trust_kwref"``.
    char_map : dict
        Mapping from first-character to list of raw JS entry strings.
    presence : str
        Sorted string of all first characters present in *char_map*; used to
        compute the hex index for each shard filename.
    """
    for char, entries in char_map.items():
        idx = presence.index(char)
        out = search_dir / f"{name}_{format(idx, 'x')}.js"
        out.write_text(
            "var searchData=\n[\n" + ",\n".join(entries) + "\n];\n",
            encoding="utf-8",
        )


def js_obj(d: dict) -> str:
    """Serialise a flat int→str dict as a JavaScript object literal.

    Used to write the three metadata objects in ``searchdata.js``::

        {
          0: "section_id_0",
          1: "section_id_1",
          ...
        }

    Parameters
    ----------
    d : dict
        Mapping from integer index to string value.
    """
    return "{\n" + ",\n".join(f'  {k}: "{v}"' for k, v in d.items()) + "\n}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <doxygen-html-dir>", file=sys.stderr)
        sys.exit(1)

    search_dir = Path(sys.argv[1]).resolve() / "search"
    searchdata = search_dir / "searchdata.js"

    if not search_dir.is_dir() or not searchdata.exists():
        print("ERROR: invalid Doxygen html directory.", file=sys.stderr)
        sys.exit(1)

    # Phase 1 — Remove any stale output files left by a previous run of this
    # script.  Stale files would confuse the search widget if section names
    # or character sets changed between runs.
    own_prefixes = tuple(s[0] for s in SECTIONS)
    for f in search_dir.glob("*.js"):
        if f.stem.startswith(own_prefixes):
            f.unlink()

    # Phase 2 — Read every shard file produced by Doxygen and route each
    # entry into the appropriate custom section bucket.
    #
    # Doxygen names its shards "<doxygen_section>_<hex>.js".  We recognise
    # two kinds of Doxygen section:
    #   "pages"             — page entries; classified by URL via RULES.
    #   CPP_SYMBOL_SECTIONS — C++ symbol entries; always go to CPPAPI.
    # Any other shard (including Doxygen's own "all_*.js" union file) is
    # deliberately skipped.  "all_*.js" is a superset of every individual
    # section file, so processing it would produce duplicate entries.
    buckets = {s[0]: defaultdict(list) for s in SECTIONS[1:]}  # skip custom_all

    for js_path in sorted(search_dir.glob("*.js")):
        parts = js_path.stem.rsplit("_", 1)
        if len(parts) != 2:
            continue
        section_name = parts[0]
        if section_name not in (CPP_SYMBOL_SECTIONS | {"pages"}):
            continue
        raw_array = read_js(js_path)
        if not raw_array:
            continue
        for raw in split_js_array(raw_array):
            raw = raw.strip().rstrip(",").strip()
            if not raw:
                continue
            char = first_char(raw)
            if section_name in ("pages", "all"):
                buckets[classify_entry(raw)][char].append(raw)
            else:
                buckets[CPPAPI][char].append(raw)

    # Phase 3 — Write the per-section, per-character shard files and build
    # the presence strings (needed both for shard filename generation and for
    # the searchdata.js metadata).
    presence = {}
    for name, char_map in buckets.items():
        presence[name] = "".join(sorted(char_map.keys()))
        write_files(search_dir, name, char_map, presence[name])

    # Phase 4 — Build and write the "All" section as the union of every other
    # section's entries.
    all_map = defaultdict(list)
    for char_map in buckets.values():
        for char, entries in char_map.items():
            all_map[char].extend(entries)
    presence[CUSTOM_ALL] = "".join(sorted(all_map.keys()))
    write_files(search_dir, CUSTOM_ALL, all_map, presence[CUSTOM_ALL])

    # Phase 5 — Rewrite searchdata.js with the new section metadata.
    # The Doxygen search widget reads three objects from this file:
    #   indexSectionsWithContent — maps section index → presence string
    #   indexSectionNames        — maps section index → section ID
    #   indexSectionLabels       — maps section index → display label
    names        = {i: s[0] for i, s in enumerate(SECTIONS)}
    labels       = {i: s[1] for i, s in enumerate(SECTIONS)}
    with_content = {i: presence[names[i]] for i in names}

    searchdata.write_text(
        f"var indexSectionsWithContent =\n{js_obj(with_content)};\n\n"
        f"var indexSectionNames =\n{js_obj(names)};\n\n"
        f"var indexSectionLabels =\n{js_obj(labels)};\n",
        encoding="utf-8",
    )

    print("Search filters patched successfully.")


if __name__ == "__main__":
    main()
