"""
Testing loading of various **elementary pieces** of TRUST datasets into the datamodel generated by trustify.
Also test that the model can reproduce the initial dataset once it has been parsed.
"""

import os
import typing
import unittest

import trustify.core.base as base
import trustify.core.misc_utilities as mutil
from tests.reference_data import (
    buildCurlyExpec,
    buildForward64_Expec,
    buildForwardExpec,
    buildMinimalExpec,
)
from trustify import TRUSTParser, TRUSTStream
from trustify.core.misc_utilities import TrustifyException, check_str_equality, logger
from trustify.core.trust_parser import TRUSTEndOfStreamException


########################################################################################
class TestCase(unittest.TestCase, mutil.UnitUtils):
    _test_dir = os.path.abspath(os.path.dirname(__file__))

    def import_and_gen_stream(self, simple_str, simplify):
        """From a string, generates the corresponding token stream that can be passed to ReadFromTokens() methods"""
        # Generate if needed
        self.generate_python_and_import("simple")
        self.mod = self._TRUG["simple"]

        # Parse the TRUST data set provided in arg
        data_ex = mutil.simplify_successive_blanks(simple_str) if simplify else simple_str
        tp = TRUSTParser()
        tp.tokenize(data_ex)
        stream = TRUSTStream(tp)
        logger.debug(f"Token list (original)    : {stream.tok}")
        logger.debug(f"Token list (low stripped): {stream.tokLow}")
        logger.debug(f"Token list has {len(stream)} items")
        return stream

    def builtin_test(self, builtin_cls, simple_str, simplify=True):
        """Generic test method taking a builtin Python type, a string representing an extract of a data set
        and returning the corresponding stream, the value, and the parser object.
        @param builtin_cls a type as defined in Python 'typing' module, e.g. 'str', or 'List[float]'
        @param simple_st a string representing the piece of dataset to be parsed
        @param simplify whether to remove successive blanks etc.
        """
        stream = self.import_and_gen_stream(simple_str, simplify)
        pars = base.Builtin_Parser.InstanciateFromBuiltin(builtin_cls)
        val = pars.readFromTokensBuiltin(stream)
        return stream, val, pars

    def generic_test(self, data, simplify=True):
        """Generic test method taking a (piece of) dataset and testing it.
        This is a (much) simpler version of base.DataSet_Parser.ReadFromTokens()
        It returns the parser stream, and the object created.
        """
        stream = self.import_and_gen_stream(data, simplify)

        # Mimick (in a minimal fashion) what is done in DataSet.ReadFromTokens():
        cls_nam = stream.probeNextLow()
        ze_cls = self._TRUG["simple"].get_parser_class(cls_nam)

        val = ze_cls.ReadFromTokens(stream)
        return stream, val

    #########################################################

    def test_utils(self):
        """Test of type (from 'typing' module) manipulation methods.

        Inputs use the legacy ``typing.Optional[X]`` form on purpose:
        ``break_type`` / ``strip_optional`` key off ``typing.Union``, which
        ``Optional[X]`` produces. PEP 604 ``X | None`` produces a different
        runtime type (``types.UnionType``) — out of scope here.
        """
        import typing as tp

        t1 = tp.Optional[tp.Annotated[list[float], "tut"]]  # noqa: UP045
        o, typs, ann = mutil.break_type(t1)
        self.assertTrue(o)
        self.assertEqual(typs, [list, float])
        self.assertEqual(ann, "tut")

        t1 = tp.Optional[list[str]]  # noqa: UP045
        o, typs, ann = mutil.break_type(t1)
        self.assertTrue(o)
        self.assertEqual(typs, [list, str])
        self.assertEqual(ann, None)

        t1 = tp.Annotated[list[float], "tut"]
        o, typs, ann = mutil.break_type(t1)
        self.assertFalse(o)
        self.assertEqual(typs, [list, float])
        self.assertEqual(ann, "tut")

        t1 = list[float]
        o, typs, ann = mutil.break_type(t1)
        self.assertFalse(o)
        self.assertEqual(typs, [list, float])
        self.assertEqual(ann, None)

        t1 = str
        o, typs, ann = mutil.break_type(t1)
        self.assertFalse(o)
        self.assertEqual(typs, [str])
        self.assertEqual(ann, None)

        t1 = tp.Optional[tp.Literal["flag1", "flag2"]]  # noqa: UP045
        o, typs, ann = mutil.break_type(t1)
        self.assertTrue(o)
        self.assertEqual(typs, [tp.Literal, "flag1", "flag2"])
        self.assertEqual(ann, None)

        t1 = tp.Optional[str]  # noqa: UP045
        o, typs, ann = mutil.break_type(t1)
        self.assertTrue(o)
        self.assertEqual(typs, [str])
        self.assertEqual(ann, None)

        t1 = tp.Optional[self.__class__]  # noqa: UP045
        typ = mutil.strip_optional(t1)
        self.assertEqual(typ, self.__class__)

    def test_parser(self):
        """Test of the TRUST parser"""
        # Test parsing quotes
        data_ex = """ system "rm -rf */toto.lml.gz" one two"""
        tp = TRUSTParser()
        tp.tokenize(data_ex)
        stream = TRUSTStream(tp)
        self.assertEqual(stream.tokLow, ["", "system", '"rm-rf*/toto.lml.gz"', "one", "two"])
        # Test EOF functionnality
        data_ex = """ # with comment #   toto      """
        stream, _, _ = self.builtin_test(str, data_ex, simplify=False)
        self.assertTrue(stream.eof())

    def test_builtin(self):
        """Test parsing int and float"""
        # Simple float first
        data_ex = """# comment #
    35.6"""
        stream, val, pars = self.builtin_test(float, data_ex, simplify=False)
        expec = 35.6
        self.assertEqual(expec, val)
        self.assertTrue(stream.eof())
        # Test writing out:
        res = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(res, data_ex).ok)
        # Should fail:
        data_ex = "toto"
        # self.builtin_test(float, data_ex, simplify=False)
        self.assertRaisesRegex(TrustifyException, "Invalid float value: 'toto'", self.builtin_test, float, data_ex)

        # Simple int now:
        data_ex = """# comment #
    35"""
        stream, val, pars = self.builtin_test(int, data_ex, simplify=False)
        expec = 35
        self.assertEqual(expec, val)
        self.assertTrue(stream.eof())
        # Test writing out:
        res = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(res, data_ex).ok)
        # Should fail:
        data_ex = "35.6"
        # self.builtin_test(int, data_ex, simplify=False)
        self.assertRaisesRegex(TrustifyException, "Invalid int value: '35.6'", self.builtin_test, int, data_ex)

        # Test parsing from typing.Literal type (corresponds to chaine(into=['single_val'] in the TRAD2)
        from typing import Literal

        data_ex = "# toto # single_val2"
        stream, val, pars = self.builtin_test(Literal["single_val1", "single_val2"], data_ex, simplify=False)
        expec = "single_val2"
        self.assertEqual(expec, val)
        self.assertTrue(stream.eof())
        # Test writing out:
        res = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(res, data_ex).ok)
        # Should fail:
        data_ex = "toto"
        # self.builtin_test(int, data_ex, simplify=False)
        self.assertRaisesRegex(TrustifyException, "Invalid int value: 'toto'", self.builtin_test, int, data_ex)

    def test_simple_str(self):
        """Test parsing simple string"""
        data_ex = """
          # with many comments
            before
          #
          toto"""
        stream, val, pars = self.builtin_test(str, data_ex, simplify=False)
        expec = "toto"
        self.assertEqual(expec, val)
        self.assertTrue(stream.eof())
        # Test writing out
        res = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(res, data_ex).ok)

    def test_builtin_list(self, fixed=False):
        """Test parsing simple float list, with user defined size or fixed size"""
        if fixed:
            sz_prefix = ""
            typ = typing.Annotated[list[float], "size_is_dim"]
            # Pretend 'dimension' keyword has been read
            from trustify.core.base import Dimension_Parser

            Dimension_Parser._DIMENSION = 3
        else:
            sz_prefix = "3"
            typ = list[float]

        data_ex = sz_prefix + " 48.5 89.2 18"
        stream, val, pars = self.builtin_test(typ, data_ex, simplify=False)
        expec = [48.5, 89.2, 18.0]
        self.assertEqual(expec, val)
        self.assertTrue(stream.eof())

        # Test writing out:
        res = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(res, data_ex).ok)

        # Changing value on the model side should change output, and not reproduce initial tokens!!
        val[1] = 39.3
        new_s = sz_prefix + " 48.5 39.3 18"
        res = "".join(pars.toDatasetTokens())
        self.assertEqual(res, new_s)
        val.pop()
        if not fixed:
            new_s = (
                " 2 48.5 39.3"  # yes a space to start with, this is the default token when generated from scratch ...
            )
            res = "".join(pars.toDatasetTokens())
            self.assertEqual(res, new_s)
        else:
            # Changing size of a fixed size list should raise
            self.assertRaisesRegex(
                TrustifyException, "has a number of items which do not match problem dimension", pars.toDatasetTokens
            )

        # Same thing stressing parser:
        data_ex = sz_prefix + """ # yop #  48.5     \n    89.2 # comment inside #  18"""
        stream, val, pars = self.builtin_test(typ, data_ex, simplify=False)  # warning: no simplification here
        expec = [48.5, 89.2, 18.0]

        self.assertTrue(expec == val)
        self.assertTrue(stream.eof())
        s = "".join(pars.toDatasetTokens())
        self.assertEqual(s, data_ex)

        # Changing value on the model side should change output, and not reproduce initial tokens!!
        val[0] = 39.3
        new_s = sz_prefix + " 39.3     \n    89.2 # comment inside #  18"
        res = "".join(pars.toDatasetTokens())
        self.assertEqual(res, new_s)
        if not fixed:
            val.pop()
            new_s = " 2 39.3     \n    89.2"  # yes a space to start with, see comment above
            res = "".join(pars.toDatasetTokens())
            self.assertEqual(res, new_s)

        # Ill formed lists
        data_ex = sz_prefix + " 48.5 89.2"
        # self.builtin_test(typing.List[float], data_ex)
        self.assertRaisesRegex(TRUSTEndOfStreamException, "Unexpected end of file", self.builtin_test, typ, data_ex)
        data_ex = sz_prefix + " 48.5 89.2 sfsf"
        # self.builtin_test(typing.List[float], data_ex)
        self.assertRaisesRegex(TrustifyException, "Invalid float value: 'sfsf'", self.builtin_test, typ, data_ex)

        # Bad size:
        if not fixed:
            data_ex = "-24 48.5 89.2 18"
            # self.builtin_test(typ, data_ex, simplify=False)
            self.assertRaisesRegex(
                TrustifyException, "Invalid number of elements in list", self.builtin_test, typ, data_ex
            )

    def test_dim_list(self):
        """Test list which size is fixed by the dimension of the problem"""
        self.test_builtin_list(fixed=True)

    def test_curly_br(self):
        """Test parsing and loading of a minimal TRUST dataset using curly braces"""
        data_ex = """
        # Some stupid test #
        read_MED_bidon # with comments #
          {
             mesh  # coucou # ze_mesh_name
             file a/complicated/path/to.med
             exclude_groups 2 toto titi
             convertAllToPoly
          }"""
        for simplify in [True, False]:
            stream, res = self.generic_test(data_ex, simplify=simplify)
            exp = buildCurlyExpec(self.mod)
            self.assertEqual(exp, res)
            self.assertTrue(stream.eof())
            if not simplify:
                # Testing writing out
                s = "".join(res.toDatasetTokens())
                self.assertTrue(check_str_equality(s, data_ex).ok)

        # Modifying data should change output!!
        res.convertalltopoly = False
        res.file = "new/file.med"
        s = "".join(res.toDatasetTokens())
        new_s = """
        # Some stupid test #
        read_MED_bidon # with comments #
          {
             mesh  # coucou # ze_mesh_name
             file new/file.med
             exclude_groups 2 toto titi
          }"""
        self.assertTrue(check_str_equality(s, new_s).ok)

        # Ill-formed dataset - missing brace
        data_ex = """
        # Some stupid test #
        read_MED_bidon # with comments #

             mesh  # coucou # ze_mesh_name
          }"""
        # self.generic_test(data_ex)
        self.assertRaisesRegex(
            TrustifyException,
            "Keyword 'read_med_bidon|lire_med_bidon' expected a opening brace '{'",
            self.generic_test,
            data_ex,
        )
        # Ill-formed dataset - missing brace
        data_ex = """
        # Some stupid test #
        read_MED_bidon # with comments # 
          {
             mesh  # coucou # ze_mesh_name
             convertAllToPoly"""
        self.assertRaisesRegex(TRUSTEndOfStreamException, "Unexpected end of file", self.generic_test, data_ex)

    def test_parser_stress(self):
        """Basic test - stressing parser"""
        data_ex = """read_MED_bidon { mesh ze_mesh_name file a/complicated/path/to.med exclude_groups 2 toto titi convertAllToPoly }"""
        stream, res = self.generic_test(data_ex, simplify=False)
        exp = buildCurlyExpec(self.mod)
        self.assertEqual(exp, res)
        self.assertTrue(stream.eof())
        # Test writing out:
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

        data_ex += " toto"  # should still parse, 'toto' being the next keyword in the stream
        stream, res = self.generic_test(data_ex, simplify=False)
        self.assertEqual(exp, res)
        self.assertFalse(stream.eof())  # but not end of stream

    def test_list_complex(self):
        """Test list of complex items"""
        from typing import Annotated

        data_ex = """# a complex list # { 
        coucou {   }   ,
        coucou { graVITe Champ_Uniforme 2 0 9.8 }
        }"""
        # We need to be able to load Coucou class before calling builtin_test (to pass the correct type), so:
        self.generate_python_and_import("simple")
        self.mod = self._TRUG["simple"]
        C = self.mod.Coucou
        stream, val, pars = self.builtin_test(Annotated[list[C], "listcoucou"], data_ex, simplify=False)
        C, UF = self.mod.Coucou, self.mod.Uniform_field
        uf = UF()
        uf.val = [0, 9.8]
        expec = [C(), C()]
        expec[1].gravite = uf
        self.assertEqual(expec, val)
        self.assertTrue(stream.eof())

        # Test writing out:
        res = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(res, data_ex).ok)

        # Changing value on the model side should change output, and not reproduce initial tokens!!
        val[0].gravite = UF()
        val[0].gravite.val = [28, 32]
        pars._pyd_value = val  # On a real dataset, this is done by _extendWithAttrTokens() in ConstrainBase_Parser
        expec = """# a complex list # { 
        coucou {
gravite  uniform_field 2 28.0 32.0   }   ,
        coucou { graVITe Champ_Uniforme 2 0 9.8 }
        }"""
        res = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(res, expec).ok)

        # Removing an item from the list
        val.pop()
        pars._pyd_value = val
        expec = """# a complex list # { 
        coucou {
gravite  uniform_field 2 28.0 32.0   }
        }"""
        res = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(res, expec).ok)

        # Adding an item to the list
        val.append(C())
        pars._pyd_value = val
        expec = """# a complex list # { 
        coucou {
gravite  uniform_field 2 28.0 32.0   }   , coucou {
 
}

        }"""  # Notice how the comma inside the list is output again as
        # was the initial one in the first list ...
        res = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(res, expec).ok)

        # Ill formed-list missing comma
        data_ex = """{  coucou {  } coucou {  }  }"""
        # self.builtin_test(typing.List[C], data_ex)
        self.assertRaisesRegex(
            TrustifyException, "expected a comma ", self.builtin_test, Annotated[list[C], "listcoucou"], data_ex
        )

        # Testing list of non-brace keywords:
        data_ex = """{ vx , vy }"""
        N = self.mod.Nom_anonyme
        stream, val, pars = self.builtin_test(Annotated[list[N], "list_nom_virgule"], data_ex, simplify=False)
        # Test writing out:
        s = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

    def test_list_of_lists(self):
        """Test nested lists ... used in coupled pbs for example"""
        from typing import Annotated

        data_ex = """  { 
        # first list # 
            { # here # pb1 , pb2 } 
        # and 2nd list # , 
            { # there # pb3 } 
        }"""
        _stream, val, pars = self.builtin_test(Annotated[list[list[str]], "list_list_nom"], data_ex, simplify=False)
        # Test writing out:
        s = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)
        # Test appending:
        un_pb = self.mod.Un_pb()
        un_pb.mot = "toto"
        val[0].append(un_pb)
        exp = """  { 
        # first list # 
            { # here # pb1 , pb2 ,
 toto } 
        # and 2nd list # , 
            { # there # pb3 } 
        }"""
        s = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(s, exp).ok)
        # Test deleting:
        val[0].pop()
        val[0].pop()
        exp = """  { 
        # first list # 
            { # here # pb1 } 
        # and 2nd list # , 
            { # there # pb3 } 
        }"""
        s = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(s, exp).ok)
        # Deleting a full sub-list
        del val[0]
        exp = """  { 
        # first list # 
            { # there # pb3 } 
        }"""  # funny thing from the way tokens are checked: first comment is preserved ...
        s = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(s, exp).ok)
        # List of lists as an attribute of a keyword:
        data_ex = """ bidon2 {   nested  { { pb1 , pb2 } , { pb3 } }   }"""
        _stream, res = self.generic_test(data_ex, simplify=False)
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

    def test_opt_attr(self):
        """Test attribute optionality. Missing required attribute should fail the parse."""
        data_ex = """
        # Invalid data with missing required attribute (file) #
        read_MED_bidon
          {
             mesh ze_mesh_name
             # file a/complicated/path/to.med #
             exclude_groups 2 toto titi
             convertAllToPoly
          }
        """
        # Should fail since mandatory attribue 'file' is missing:
        self.assertRaisesRegex(
            TrustifyException,
            "Attribute 'file' is mandatory for keyword 'read_med_bidon|lire_med_bidon'",
            self.generic_test,
            data_ex,
        )

        # Keyword with all optionals should accept no attributes at all:
        data_ex = """coucou { }"""
        stream, res = self.generic_test(data_ex)
        MB = self.mod.Coucou
        exp = MB()
        self.assertEqual(exp, res)
        self.assertTrue(stream.eof())
        # Test writing out:
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

    def test_list_opt(self):
        """List of objects having only optional attributes. If an item was incorrect, this was looping
        indefinitely since errors on keywords with only optional attributes were not properly diagnosed.
        See code in ConstrainBase_Parser::_readFromTokens_no_braces()
        """
        from typing import Annotated

        data_ex = """{ 25 ,  64 }"""
        self.generate_python_and_import("simple")
        self.mod = self._TRUG["simple"]
        B = self.mod.Bidon3
        stream, val, pars = self.builtin_test(Annotated[list[B], "list_bidon3"], data_ex, simplify=False)
        b1, b2 = B(), B()
        b1.ze_int, b2.ze_int = 25, 64
        expec = [b1, b2]
        self.assertEqual(expec, val)
        self.assertTrue(stream.eof())

        # Test writing out:
        res = "".join(pars.toDatasetTokens())
        self.assertTrue(check_str_equality(res, data_ex).ok)

        ## Now the faulty behavior that was looping forever in some cases:
        data_ex = """{ chaine }"""
        # stream, val, pars = self.builtin_test(Annotated[List[B], "list_bidon3"], data_ex, simplify=False)
        self.assertRaisesRegex(
            TrustifyException,
            "Could not read object of type 'List_bidon3' inside list! Word 'chaine' was unexpected",
            self.builtin_test,
            Annotated[list[B], "list_bidon3"],
            data_ex,
        )

    def test_synonyms(self):
        """Test synonyms"""
        data_ex = """
        # Some stupid test with syno #
        read_MED_bidon
          {
             maillage ze_mesh_name
             fichier a/complicated/path/to.med
             exclude_groups 2 toto titi
             convertAllToPoly
          }"""
        for simplify in [True, False]:
            stream, res = self.generic_test(data_ex, simplify=simplify)
            exp = buildCurlyExpec(self.mod)
            self.assertEqual(exp, res)
            self.assertTrue(stream.eof())
            if not simplify:
                # Test writing out:
                s = "".join(res.toDatasetTokens())
                self.assertTrue(check_str_equality(s, data_ex).ok)

    def test_no_curly_br(self):
        """Testing keywords with no curly braces"""
        # Standard case
        data_ex = """uniform_field 3 34.6 12.8 90.9"""
        stream, res = self.generic_test(data_ex)
        UF = self.mod.Uniform_field
        # Build expected value
        exp = UF()
        exp.val = [34.6, 12.8, 90.9]
        self.assertEqual(exp, res)
        self.assertTrue(stream.eof())
        # Test writing out:
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

        # The below should parse - 'toto' can be considered the next keyword in the stream
        data_ex2 = data_ex + " toto "
        stream, res = self.generic_test(data_ex2)
        self.assertEqual(exp, res)
        #   here we re not at EOF, since 'toto' is there
        self.assertFalse(stream.eof())
        # With an optional flag and more spaces in between!
        data_ex = """
        # Example no curly brace with optional #
        uniform_field   flag_bidon  3   34.6  12.8 90.9
           flag_bidon2  2 15   29"""
        for simplify in [True, False]:
            stream, res = self.generic_test(data_ex, simplify=simplify)
            exp = UF()
            exp.val, exp.val2 = [34.6, 12.8, 90.9], [15, 29]
            exp.flag_bidon, exp.flag_bidon2 = "flag_bidon", "flag_bidon2"
            self.assertEqual(exp, res)
            self.assertTrue(stream.eof())
            if not simplify:
                # Test writing out:
                s = "".join(res.toDatasetTokens())
                self.assertTrue(check_str_equality(s, data_ex).ok)

        # Same story with next keyword:
        data_ex2 = data_ex + " toto "
        stream, res = self.generic_test(data_ex2)
        self.assertEqual(exp, res)
        self.assertFalse(stream.eof())

        # Ill-formed dataset (missing attribute):
        data_ex = """
        # Ill-formed #
        uniform_field flag_bidon
        """
        # self.generic_test(data_ex)
        self.assertRaisesRegex(TRUSTEndOfStreamException, "Unexpected end of file", self.generic_test, data_ex)
        # Ill-formed dataset (missing values)
        data_ex = """
        # Ill-formed #
        uniform_field 3 34.6 12.8
        """
        # self.generic_test(data_ex)
        self.assertRaisesRegex(TRUSTEndOfStreamException, "Unexpected end of file", self.generic_test, data_ex)

    def test_complex_attr(self):
        """Testing complex attributes (with a prescribed type)"""
        data_ex = """
          coucou {
            attr_bidon champ_uniforme 2 0  9.8  # using attr synonyms too #
          }"""
        stream, res = self.generic_test(data_ex, simplify=False)
        MB, UF = self.mod.Coucou, self.mod.Uniform_field
        # Build expected value
        exp, uf = MB(), UF()
        uf.val = [0, 9.8]
        exp.attr_bidon = uf
        self.assertEqual(exp, res)
        self.assertTrue(stream.eof())
        # Test writing out:
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

        # Test changing one of the value
        res.attr_bidon.val[0] = -25
        data_ex = """
          coucou {
            attr_bidon champ_uniforme 2 -25  9.8  # using attr synonyms too #
          }"""
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

        # Settng a complete new list
        res.attr_bidon.val = [5, 6, 7]  # Complete new list
        data_ex = """
          coucou {
            attr_bidon champ_uniforme 3 5.0 6.0 7.0  # using attr synonyms too #
          }"""  # Note how the comment is attached to the closing brace...
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

        # Seting an invalid type (pydantic should complain):
        import pydantic

        self.assertRaisesRegex(
            pydantic.ValidationError, "validation error for Uniform_field", setattr, res.attr_bidon, "val", "qsd"
        )

        # Disabling an attribute
        res.attr_bidon = None
        data_ex = """
          coucou {  # using attr synonyms too #
          }"""
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

        # Assigning a complete new object for an attribute
        res.gravite = UF()
        res.gravite.val = [2, 3]
        data_ex = """
          coucou {
gravite  uniform_field 2 2.0 3.0  # using attr synonyms too #
          }"""  # I know indentation sucks ...
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

        # Adding unexpected attribute should raise:
        data_ex = """ coucou { blop }"""
        # self.generic_test(data_ex, simplify=False)
        self.assertRaisesRegex(
            TrustifyException, "Unexpected attribute 'blop' in keyword 'coucou'", self.generic_test, data_ex
        )

    def test_add_rm_attr(self):
        """Testing adding an attribute to a keyword and checking output ok"""
        data_ex = """
        # Some stupid test with syno #
        read_MED_bidon
          {
             maillage ze_mesh_name
             fichier a/complicated/path/to.med
             exclude_groups 2 toto titi
             convertAllToPoly
          }"""

        stream, res = self.generic_test(data_ex, simplify=False)
        exp = buildCurlyExpec(self.mod)
        self.assertEqual(exp, res)
        self.assertTrue(stream.eof())
        # Adding a (valid) attribute
        res.no_family_names_from_group_names = True
        data_expected = """
        # Some stupid test with syno #
        read_MED_bidon
          {
             maillage ze_mesh_name
             fichier a/complicated/path/to.med
             exclude_groups 2 toto titi
             convertAllToPoly
no_family_names_from_group_names 
          }"""
        # (Yes I know this is poorly indented and space after "no_fam..." needs to be kept!)
        # Test writing out:
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_expected).ok)
        # Removing an attribute (setting to None):
        res.mesh = None
        data_expected = """
        # Some stupid test with syno #
        read_MED_bidon
          {
             fichier a/complicated/path/to.med
             exclude_groups 2 toto titi
             convertAllToPoly
no_family_names_from_group_names 
          }"""
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_expected).ok)

    def test_inheritance(self):
        """Testing inheritance - gravite expects a 'field_base' of which 'champ_uniform' is a child
        Also test inherited members: bidon should inherit member 'top_attr' from toto_base
        """
        data_ex = """
          coucou {
            gravite champ_uniforme 2 0 9.8
          }"""
        for simplify in [True, False]:
            stream, res = self.generic_test(data_ex, simplify=simplify)
            MB, UF = self.mod.Coucou, self.mod.Uniform_field
            # Build expected value
            exp, uf = MB(), UF()
            uf.val = [0, 9.8]
            exp.gravite = uf
            # Test
            self.assertEqual(exp, res)
            self.assertTrue(stream.eof())
            if not simplify:
                # Test writing out:
                s = "".join(res.toDatasetTokens())
                self.assertTrue(check_str_equality(s, data_ex).ok)

        # Changing inherited attribute should change output:
        FB = self.mod.Field_base
        res.gravite = FB()
        s = "".join(res.toDatasetTokens())
        new_s = """
          coucou {
            gravite field_base
          }"""
        self.assertTrue(check_str_equality(s, new_s).ok)

        # Wrong inheritance should raise:
        data_ex = """
          coucou {
            gravite coucou { }
          }
        """
        # offset, res = self.generic_test(data_ex)
        self.assertRaisesRegex(Exception, "Invalid TRUST keyword: 'coucou'", self.generic_test, data_ex)

        # Member inheritance
        data_ex = """bidon { 
            top_attr_syno nimp
            ma_liste { }
            }"""
        stream, res = self.generic_test(data_ex, simplify=False)
        exp = self.mod.Bidon()
        exp.top_attr = "nimp"
        exp.ma_liste = []
        self.assertEqual(exp, res)
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

    def test_forward_decl_1(self):
        """Testing forward declaration and 'read' keyword.
        This uses the main loop from Dataset."""
        from trustify.core.base import Declaration_Parser

        # Simple forward declaration parsing
        data_ex = """  # with comments #
        lire_med_bidon     rmed"""
        for simplify in [True, False]:
            stream = self.import_and_gen_stream(data_ex, simplify)
            exp = self.mod.Declaration()
            exp.identifier, exp.ze_type = "rmed", self.mod.Read_med_bidon
            res = Declaration_Parser.ReadFromTokens(stream)
            self.assertTrue(stream.eof())
            self.assertEqual(exp, res)
            if not simplify:
                # Test writing out:
                s = "".join(res.toDatasetTokens())
                self.assertTrue(check_str_equality(s, data_ex).ok)
        # Test invalid decl
        data_ex = """ blop blip """
        stream = self.import_and_gen_stream(data_ex, False)
        self.assertRaisesRegex(
            TrustifyException, "Invalid TRUST keyword: 'blop'", Declaration_Parser.ReadFromTokens, stream
        )

    def test_forward_decl_2(self):
        """Forward declaration test. With a non-interprete keyword."""
        # Valid dataset
        data_ex = """champ_uniforme gravite
                     # comment in the middle #
                     read    gravite  2   0.0    9.8"""
        stream = self.import_and_gen_stream(data_ex, simplify=False)
        ds_cls = self.mod.Dataset_Parser
        res = ds_cls.ReadFromTokens(stream)
        self.assertEqual(len(res.entries), 2)
        self.assertTrue(stream.eof())
        UF, D, RD = self.mod.Uniform_field, self.mod.Declaration, self.mod.Read
        decl = D()
        decl.identifier, decl.ze_type = "gravite", UF
        r, f, vals = RD(), UF(), [0, 9.8]
        f.val = vals
        r.identifier = "gravite"
        r.obj = f
        self.assertEqual(res.entries[0], decl)
        self.assertEqual(res.entries[1], r)
        # Test writing out:
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

        # Changing read object completely:
        f2 = UF()
        f2.val = [5, 6, 7]
        res.entries[1].obj = f2
        s = "".join(res.toDatasetTokens())
        data_ex = """champ_uniforme gravite
                     # comment in the middle #
                     read    gravite 3 5.0 6.0 7.0"""
        self.assertTrue(check_str_equality(s, data_ex).ok)

        # Invalid datasets
        #    Misformatted fwd decl:
        data_ex = """champ_uniforme 35
                     coucou { }"""
        stream = self.import_and_gen_stream(data_ex, simplify=False)
        # res = ds_cls.ReadFromTokens(stream)
        self.assertRaisesRegex(
            TrustifyException,
            "Invalid identifier '35' in forward declaration of type 'champ_uniforme'",
            ds_cls.ReadFromTokens,
            stream,
        )
        #    Misformatted - trying to make a forward declaration with an interprete:
        data_ex = """champ_uniforme gravite
                     lire_med forward"""
        stream = self.import_and_gen_stream(data_ex, simplify=False)
        # res = ds_cls.ReadFromTokens(stream)
        self.assertRaisesRegex(
            TrustifyException, "Keyword 'read_med|lire_med' expected a opening brace ", ds_cls.ReadFromTokens, stream
        )
        #    Wrong reference:
        data_ex = """champ_uniforme gravite
                     read toto"""
        stream = self.import_and_gen_stream(data_ex, simplify=False)
        # res = ds_cls.ReadFromTokens(stream)
        self.assertRaisesRegex(
            TrustifyException, "Referencing object 'toto' .* not declared", ds_cls.ReadFromTokens, stream
        )

    def test_declaration_toDatasetTokens_emits_class_name_for_programmatic_pyd(self):
        """Audit 1.2: `Declaration_Parser.toDatasetTokens` had the same
        anti-pattern as the previously-fixed `_getClsTokens` —
        comparing `tokens.low()` (a list) to `""` (a string) is
        always True, so the dead else-branch that synthesizes a class
        name from `ze_type.__name__` never fired. Parsed Declarations
        worked by coincidence (they overwrite `_tokens["cls_nam"]`
        during `readFromTokens_impl`); a Declaration built directly
        in Python (LSP write-side, programmatic format_dataset)
        emitted the empty placeholder's `.orig()` — the parser-base
        class name "declaration" rather than the actual ze_type."""
        from trustify.core.base import Declaration_Parser

        # Ensure the simple schema is loaded so the pyd classes exist.
        self.import_and_gen_stream("", simplify=False)

        decl = self.mod.Declaration()
        decl.identifier = "gravite"
        decl.ze_type = self.mod.Uniform_field

        parser = Declaration_Parser(decl)
        out = "".join(parser.toDatasetTokens())
        self.assertIn(
            "uniform_field",
            out.lower(),
            f"Declaration emitted {out!r}; expected ze_type name `uniform_field` "
            "(the dead else-branch must fire when `_tokens['cls_nam']` was not "
            "populated from a real stream read)",
        )

    def test_read_parser_restores_read_type_when_inner_parse_raises(self):
        """Audit 4.1: `Read_Parser.readFromTokens_impl` flips
        `cls._ze_type._read_type` to False before calling the inner
        `ReadFromTokens` and restores it afterwards. Without a
        try/finally, an exception from the inner call leaves the
        CLASS-level attribute stuck at False for the rest of the
        process — every subsequent parse of that type would skip the
        class-name read, silently misbehaving. (And, ironically, would
        corrupt every later test that reads this same attribute.)"""
        from unittest.mock import patch

        from trustify import Dataset_Parser

        data_ex = """champ_uniforme gravite
                     read    gravite  2   0.0    9.8"""
        stream = self.import_and_gen_stream(data_ex, simplify=False)

        # Uniform_field is the target of `read gravite ...`; its
        # parser class holds the _read_type that the swap mutates.
        # Reset explicitly: the same bug we're testing for could
        # have corrupted this attribute in a previous test run.
        UF_pars = self.mod.get_parser_class("Uniform_field")
        saved = UF_pars._read_type
        UF_pars._read_type = True
        try:
            with (
                patch.object(UF_pars, "ReadFromTokens", side_effect=RuntimeError("simulated parse failure")),
                self.assertRaises(RuntimeError),
            ):
                Dataset_Parser.ReadFromTokens(stream)
            self.assertTrue(
                UF_pars._read_type,
                "Read_Parser.readFromTokens_impl must restore _ze_type._read_type even when the inner parse raises",
            )
        finally:
            UF_pars._read_type = saved

    def test_read_parser_restores_read_type_when_inner_write_raises(self):
        """Audit 4.1 (symmetric): `Read_Parser.toDatasetTokens` flips
        `tok_obj_pars.__class__._read_type` to False during the
        inner `toDatasetTokens` and must restore it on exception."""
        from unittest.mock import patch

        from trustify import Dataset_Parser

        data_ex = """champ_uniforme gravite
                     read    gravite  2   0.0    9.8"""
        stream = self.import_and_gen_stream(data_ex, simplify=False)

        UF_pars = self.mod.get_parser_class("Uniform_field")
        saved = UF_pars._read_type
        UF_pars._read_type = True
        try:
            # Parse first (with healthy _read_type) to get a valid Read
            # pyd value to drive the write side.
            res = Dataset_Parser.ReadFromTokens(stream)
            with (
                patch.object(UF_pars, "toDatasetTokens", side_effect=RuntimeError("simulated write failure")),
                self.assertRaises(RuntimeError),
            ):
                "".join(res.toDatasetTokens())
            self.assertTrue(
                UF_pars._read_type,
                "Read_Parser.toDatasetTokens must restore _ze_type._read_type even when the inner write raises",
            )
        finally:
            UF_pars._read_type = saved

    def test_read_parser_ze_type_not_leaked_as_class_attribute(self):
        """Audit 4.2: `Read_Parser._ze_type` used to be a process-global
        class attribute clobbered mid-parse by
        `Dataset_Parser._prepare_read_instruction`. Two concurrent
        parses in the same process raced on the slot — the realistic
        scenario being an LSP server hosting multiple open files in
        multiple threads, or any callback (hover, completion, doc-gen
        probe) that triggers a fresh parse while the outer parse is
        between `_prepare_read_instruction` and the matching
        `Read_Parser.readFromTokens_impl`.

        The fix threads the type via instance state on the
        Read_Parser instance. The class attribute therefore stays at
        its default (None) across parses; this test asserts that
        invariant."""
        from trustify import Dataset_Parser
        from trustify.core.base import Read_Parser

        data_ex = """champ_uniforme gravite
                     read    gravite  2   0.0    9.8"""
        stream = self.import_and_gen_stream(data_ex, simplify=False)

        # Reset baseline: any earlier test in this run (e.g. the 4.1
        # tests above) could have left the class-level slot populated
        # under the old behaviour. We're testing the post-fix
        # invariant — the class attr must stay None after a parse.
        Read_Parser._ze_type = None
        Dataset_Parser.ReadFromTokens(stream)
        self.assertIsNone(
            Read_Parser._ze_type,
            "Read_Parser._ze_type leaked across parses as a class "
            "attribute. The type must live on the Read_Parser instance "
            "so concurrent parses cannot race on it.",
        )

    def test_lookups_raise_internal_error_when_schema_not_activated(self):
        """Audit 5.7: keyword-resolution helpers used to silently
        degrade when `cls._schema_module` was None — `_has_class`
        returned False, `GetAllClassesFromSyno`'s syno_map fell back
        to `{}`, and the user saw a generic "Invalid TRUST keyword"
        error pointing at their dataset rather than at the real cause
        (the schema-activation step was missed, almost always a
        concurrent-schema bug — see CLAUDE.md "Multi-schema
        coexistence" gotcha).

        Now: raise `TrustifyInternalError` from `_has_class` and
        `_resolve_attr` when `_schema_module is None`, so the failure
        is attributed to trustify itself (with traceback via the CLI
        routing from audit 5.4) instead of masquerading as a user
        input error.
        """
        from trustify import TrustifyInternalError
        from trustify.core.base import Abstract_Parser

        class _Probe(Abstract_Parser):
            pass

        _Probe._schema_module = None

        with self.assertRaises(TrustifyInternalError) as cm:
            _Probe._has_class("any_keyword")
        self.assertIn("schema", str(cm.exception).lower())

        with self.assertRaises(TrustifyInternalError) as cm:
            _Probe._resolve_attr("Anything")
        self.assertIn("schema", str(cm.exception).lower())

    def test_forward_decl_3(self):
        from trustify import Dataset_Parser

        # Small datasets using forward declarations
        data_ex = """
        lire_med_bidon   rmed    # bidon because not an interpret #
        coucou cb

        Read  rmed
          {
             mesh ze_mesh_name
             file a/complicated/path/to.med
          }

        read    cb {   }"""

        for simplify in [True, False]:
            stream = self.import_and_gen_stream(data_ex, simplify)
            res = Dataset_Parser.ReadFromTokens(stream)
            self.assertEqual(len(res.entries), 4)
            self.assertTrue(stream.eof())
            exp0, exp1, exp2, exp3 = buildForwardExpec(self.mod)
            self.assertEqual(exp0, res.entries[0])  # Forward decl
            self.assertEqual(exp1, res.entries[1])  # Coucou cb
            self.assertEqual(exp2, res.entries[2])  # read rmed
            self.assertEqual(exp3, res.entries[3])  # read cb
            if not simplify:
                # Test writing out:
                s = "".join(res.toDatasetTokens())
                self.assertTrue(check_str_equality(s, data_ex).ok)

    def test_64b(self):
        """Test for 64b keywords"""
        from trustify import Dataset_Parser

        data_ex = """
        dimension 3
        
        lire_med_bidon_64 rmed    # Forward decl 64b #
        
        lire_med_64 {       # Direct invocation #
             mesh ze_mesh_name
             file a/complicated/path/to.med
          }"""
        stream = self.import_and_gen_stream(data_ex, simplify=False)
        res = Dataset_Parser.ReadFromTokens(stream)
        self.assertEqual(len(res.entries), 3)
        self.assertTrue(stream.eof())
        exp0 = buildForward64_Expec(self.mod)
        self.assertEqual(exp0, res.entries[1])  # Forward decl
        # Test writing out:
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

    def test_dim_pars(self):
        """Test Dimension_Parser class - output was buggy"""
        from trustify import Dataset_Parser

        data_ex = "dimension # coucou # 2"
        stream = self.import_and_gen_stream(data_ex, simplify=False)
        res = Dataset_Parser.ReadFromTokens(stream)
        s = "".join(res.toDatasetTokens())
        self.assertTrue(check_str_equality(s, data_ex).ok)

    def test_complete_dataset(self):
        """Complete (small) dataset with foward declarations etc..."""
        from trustify import Dataset_Parser

        data_ex = """
        # Some stupid test #
        champ_uniforme gravite
        nom coucou
        read gravite 2 28 32   # Keyword with no brace #
        read coucou toto
        lire_MED
          {
             mesh ze_mesh_name
             file a/complicated/path/to.med
             exclude_groups 2 toto titi
             convertAllToPoly
          }"""

        for simplify in [True, False]:
            stream = self.import_and_gen_stream(data_ex, simplify)
            res = Dataset_Parser.ReadFromTokens(stream)
            self.assertEqual(len(res.entries), 5)
            self.assertTrue(stream.eof())

            exp = buildMinimalExpec(self.mod)
            for i in range(5):
                self.assertEqual(exp[i], res.entries[i])
            if not simplify:
                # Test writing out:
                s = "".join(res.toDatasetTokens())
                self.assertTrue(check_str_equality(s, data_ex).ok)

    def test_validate(self):
        """Test validate functionality"""
        from pydantic import ValidationError

        from trustify import Dataset_Parser

        data_ex = data_ex = """
        # Some stupid test #
        champ_uniforme gravite
        read gravite 2 28 32   # Keyword with no brace #
        """
        stream = self.import_and_gen_stream(data_ex, False)
        res = Dataset_Parser.ReadFromTokens(stream)
        g = res.get("gravite")
        g.val[0] = "sdfs"  # a str instead of a float! Forbidden, but can not be seen at assignation time!
        self.assertRaisesRegex(
            ValidationError, "Input should be a valid number, unable to parse string as a number", g.self_validate
        )


if __name__ == "__main__":
    unittest.main()
